"""Adding pokemon model

Revision ID: d2d59603e94d
Revises: 617784fce9a5
Create Date: 2024-07-04 16:10:34.146636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2d59603e94d'
down_revision: Union[str, None] = '617784fce9a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pokemons_name'), 'pokemons', ['name'], unique=False)
    op.create_index(op.f('ix_pokemons_type'), 'pokemons', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pokemons_type'), table_name='pokemons')
    op.drop_index(op.f('ix_pokemons_name'), table_name='pokemons')
    # ### end Alembic commands ###
